config/routes.rb
Balasevic::Application.routes.draw do
  resources :subscribers, :only => [:new, :create], :path => '', :path_names => {:new => ''}
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :email, :travel, :zip_code
  
  validates_presence_of :email, :message => "Oh no, looks like you forgot something"
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, :message => "Looks like something isn't right with your email address"
  
  validates_presence_of :zip_code, :message => "Oh no, looks like you forgot something"
  validates_format_of :zip_code, :with => /(^([0-9]{5})(?:[-\s]*([0-9]{4}))?$)|(^([A-Z][0-9][A-Z])\s*([0-9][A-Z][0-9])$)/, :message => "Looks like something isn't right with your postal code"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /
  def create
    @subscriber = Subscriber.new(params[:subscriber])

    if @subscriber.save
      redirect_to "/", notice: "Thanks! We'll send you an email when we have more information."
    else
      render :action => "new"
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Balasevic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="home">
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38420742-1']);
  _gaq.push(['_setDomainName', 'balasevicusa.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<header id="top">
  <div id="wrap">
    <a id="logo"></a>
  </div>
</header>


<%= yield %>

</body>
</html>

app/views/subscribers/_form.html.erb
<%= simple_form_for @subscriber do |f| %>
  <%= f.input :email, :label => "Email Address:", :placeholder => "balasevic.rocks@email.com" %>
  <%= f.input :zip_code, :label => "Postal Code:", :placeholder => "12345" %>
  <%= f.button :submit, "Submit" %>
  <% if flash[:notice] %>
  <span class="success"><%= flash[:notice] %></span>
  <% end %>
  <br class="clear">
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Zip code</th>
    <th>Travel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscribers.each do |subscriber| %>
  <tr>
    <td><%= subscriber.email %></td>
    <td><%= subscriber.zip_code %></td>
    <td><%= subscriber.travel %></td>
    <td><%= link_to 'Show', subscriber %></td>
    <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
    <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<div class="wrap">
  <h1>
    Djordje Balasevic<br>
    Sjeverno Americka<br>
    Turneja 2013
  </h1>

  <%= render 'form' %>

</div>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @subscriber.email %>
</p>

<p>
  <b>Zip code:</b>
  <%= @subscriber.zip_code %>
</p>

<p>
  <b>Travel:</b>
  <%= @subscriber.travel %>
</p>


<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>